/**
 * Белые и чёрные списки SQL-лаборатории (17-security.md: «белый список узлов и
 * функций»). Функция вне белого списка — отказ; чёрный список даёт понятную
 * причину для опасных функций и страхует белый от случайного расширения.
 * Сравнение с белым списком — точное (встроенные имена в нижнем регистре),
 * с чёрным — без учёта регистра.
 */

const AGGREGATES = [
  'count',
  'sum',
  'avg',
  'min',
  'max',
  'string_agg',
  'array_agg',
  'bool_and',
  'bool_or',
  'every',
  'bit_and',
  'bit_or',
  'bit_xor',
  'any_value',
  'stddev',
  'stddev_pop',
  'stddev_samp',
  'variance',
  'var_pop',
  'var_samp',
  'corr',
  'covar_pop',
  'covar_samp',
  'regr_avgx',
  'regr_avgy',
  'regr_count',
  'regr_intercept',
  'regr_r2',
  'regr_slope',
  'regr_sxx',
  'regr_sxy',
  'regr_syy',
  'percentile_cont',
  'percentile_disc',
  'mode',
  'json_agg',
  'jsonb_agg',
  'json_object_agg',
  'jsonb_object_agg',
]

const WINDOW = [
  'row_number',
  'rank',
  'dense_rank',
  'percent_rank',
  'cume_dist',
  'ntile',
  'lag',
  'lead',
  'first_value',
  'last_value',
  'nth_value',
]

const MATH = [
  'abs',
  'cbrt',
  'ceil',
  'ceiling',
  'degrees',
  'div',
  'exp',
  'factorial',
  'floor',
  'gcd',
  'lcm',
  'ln',
  'log',
  'log10',
  'min_scale',
  'mod',
  'pi',
  'power',
  'radians',
  'round',
  'scale',
  'sign',
  'sqrt',
  'trim_scale',
  'trunc',
  'width_bucket',
  'acos',
  'asin',
  'atan',
  'atan2',
  'cos',
  'cot',
  'sin',
  'tan',
  'acosd',
  'asind',
  'atand',
  'atan2d',
  'cosd',
  'cotd',
  'sind',
  'tand',
  'sinh',
  'cosh',
  'tanh',
  'asinh',
  'acosh',
  'atanh',
  'random',
  'num_nulls',
  'num_nonnulls',
]

const STRINGS = [
  'ascii',
  'bit_length',
  'btrim',
  'char_length',
  'character_length',
  'chr',
  'concat',
  'concat_ws',
  'decode',
  'encode',
  'format',
  'initcap',
  'is_normalized',
  'left',
  'length',
  'lower',
  'lpad',
  'ltrim',
  'md5',
  'normalize',
  'octet_length',
  'overlay',
  'position',
  'quote_ident',
  'quote_literal',
  'quote_nullable',
  'regexp_count',
  'regexp_instr',
  'regexp_like',
  'regexp_match',
  'regexp_matches',
  'regexp_replace',
  'regexp_split_to_array',
  'regexp_split_to_table',
  'regexp_substr',
  'replace',
  'reverse',
  'right',
  'rpad',
  'rtrim',
  'similar_to_escape',
  'split_part',
  'starts_with',
  'string_to_array',
  'string_to_table',
  'strpos',
  'substr',
  'substring',
  'to_hex',
  'translate',
  'upper',
  'to_char',
  'to_number',
  // Расширения в схеме extensions: unaccent, pg_trgm
  'unaccent',
  'similarity',
  'word_similarity',
  'strict_word_similarity',
  // Полнотекстовый поиск
  'to_tsvector',
  'to_tsquery',
  'plainto_tsquery',
  'phraseto_tsquery',
  'websearch_to_tsquery',
  'ts_rank',
  'ts_rank_cd',
  'ts_headline',
]

const DATES = [
  'age',
  'date_add',
  'date_bin',
  'date_part',
  'date_subtract',
  'date_trunc',
  'extract',
  'isfinite',
  'justify_days',
  'justify_hours',
  'justify_interval',
  'make_date',
  'make_interval',
  'make_time',
  'make_timestamp',
  'make_timestamptz',
  'overlaps',
  'timezone',
  'to_date',
  'to_timestamp',
  // Текущее время: результат зависит от момента выполнения
  'now',
  'clock_timestamp',
  'statement_timestamp',
  'transaction_timestamp',
]

const JSON_READ = [
  'array_to_json',
  'json_array_elements',
  'json_array_elements_text',
  'json_array_length',
  'json_build_array',
  'json_build_object',
  'json_each',
  'json_each_text',
  'json_extract_path',
  'json_extract_path_text',
  'json_object_keys',
  'json_strip_nulls',
  'json_to_record',
  'json_to_recordset',
  'json_typeof',
  'jsonb_array_elements',
  'jsonb_array_elements_text',
  'jsonb_array_length',
  'jsonb_build_array',
  'jsonb_build_object',
  'jsonb_each',
  'jsonb_each_text',
  'jsonb_extract_path',
  'jsonb_extract_path_text',
  'jsonb_object_keys',
  'jsonb_path_exists',
  'jsonb_path_match',
  'jsonb_path_query',
  'jsonb_path_query_array',
  'jsonb_path_query_first',
  'jsonb_pretty',
  'jsonb_strip_nulls',
  'jsonb_to_record',
  'jsonb_to_recordset',
  'jsonb_typeof',
  'row_to_json',
  'to_json',
  'to_jsonb',
]

const ARRAYS = [
  'array_append',
  'array_cat',
  'array_dims',
  'array_length',
  'array_lower',
  'array_ndims',
  'array_position',
  'array_positions',
  'array_prepend',
  'array_remove',
  'array_replace',
  'array_to_string',
  'array_upper',
  'cardinality',
  'generate_series',
  'generate_subscripts',
  'trim_array',
  'unnest',
  'gen_random_uuid',
]

/** PostGIS: только чтение и анализ геометрий (без функций каталога и DDL). */
const POSTGIS = [
  'geometry',
  'geography',
  'box2d',
  'box3d',
  'st_angle',
  'st_area',
  'st_asbinary',
  'st_asewkt',
  'st_asgeojson',
  'st_astext',
  'st_azimuth',
  'st_boundary',
  'st_buffer',
  'st_centroid',
  'st_closestpoint',
  'st_clusterdbscan',
  'st_clusterkmeans',
  'st_collect',
  'st_concavehull',
  'st_contains',
  'st_convexhull',
  'st_coveredby',
  'st_covers',
  'st_crosses',
  'st_difference',
  'st_dimension',
  'st_disjoint',
  'st_distance',
  'st_distancesphere',
  'st_distancespheroid',
  'st_dump',
  'st_dumppoints',
  'st_dwithin',
  'st_endpoint',
  'st_envelope',
  'st_equals',
  'st_expand',
  'st_extent',
  'st_exteriorring',
  'st_flipcoordinates',
  'st_force2d',
  'st_geogfromtext',
  'st_geohash',
  'st_geometryn',
  'st_geometrytype',
  'st_geomfromewkt',
  'st_geomfromgeojson',
  'st_geomfromtext',
  'st_geomfromwkb',
  'st_hausdorffdistance',
  'st_hexagongrid',
  'st_intersection',
  'st_intersects',
  'st_isempty',
  'st_isvalid',
  'st_isvalidreason',
  'st_length',
  'st_lineinterpolatepoint',
  'st_linelocatepoint',
  'st_linemerge',
  'st_linesubstring',
  'st_makeenvelope',
  'st_makeline',
  'st_makepoint',
  'st_makepolygon',
  'st_makevalid',
  'st_maxdistance',
  'st_multi',
  'st_npoints',
  'st_numgeometries',
  'st_numpoints',
  'st_orderingequals',
  'st_overlaps',
  'st_perimeter',
  'st_point',
  'st_pointn',
  'st_pointonsurface',
  'st_project',
  'st_reduceprecision',
  'st_relate',
  'st_reverse',
  'st_segmentize',
  'st_setsrid',
  'st_shortestline',
  'st_simplify',
  'st_simplifypreservetopology',
  'st_snaptogrid',
  'st_split',
  'st_squaregrid',
  'st_srid',
  'st_startpoint',
  'st_subdivide',
  'st_symdifference',
  'st_tileenvelope',
  'st_touches',
  'st_transform',
  'st_union',
  'st_within',
  'st_x',
  'st_xmax',
  'st_xmin',
  'st_y',
  'st_ymax',
  'st_ymin',
  'st_z',
]

/** Категории белого списка — для README и подсказки в ошибке. */
export const FUNCTION_GROUPS: Readonly<Record<string, readonly string[]>> = {
  агрегаты: AGGREGATES,
  оконные: WINDOW,
  математика: MATH,
  строки: STRINGS,
  даты: DATES,
  json: JSON_READ,
  массивы: ARRAYS,
  postgis: POSTGIS,
}

const ALLOWED_FUNCTIONS = new Set(Object.values(FUNCTION_GROUPS).flat())

/** Функции, результат которых зависит от момента выполнения или случая, — не кэшируются. */
export const VOLATILE_FUNCTIONS = new Set([
  'now',
  'clock_timestamp',
  'statement_timestamp',
  'transaction_timestamp',
  'random',
  'gen_random_uuid',
])

/** Чёрный список: префиксы и точные имена (нижний регистр). */
const DENIED_PREFIXES = [
  'pg_', // pg_sleep*, pg_read_*, pg_ls_*, pg_stat_*, pg_advisory*, pg_terminate_backend…
  'txid',
  'lo_',
  'dblink',
  'postgis_',
  'plpgsql',
  'pgp_',
  'binary_upgrade',
  'has_',
  'to_reg',
]
const DENIED_NAMES = new Set([
  'set_config',
  'current_setting',
  'nextval',
  'setval',
  'currval',
  'lastval',
  'loread',
  'lowrite',
  'version',
  'current_database',
  'current_catalog',
  'current_schema',
  'current_schemas',
  'current_user',
  'current_role',
  'session_user',
  'system_user',
  'current_query',
  'inet_client_addr',
  'inet_client_port',
  'inet_server_addr',
  'inet_server_port',
  'row_security_active',
  'obj_description',
  'col_description',
  'shobj_description',
  'format_type',
  'ts_stat',
  'ts_rewrite',
  'setseed',
  'set_limit',
  'st_estimatedextent',
])

/** Функция запрещена явно (чёрный список, без учёта регистра). */
export function isDeniedFunction(name: string): boolean {
  const lower = name.toLowerCase()
  if (DENIED_NAMES.has(lower)) return true
  if (lower.includes('xml')) return true // query_to_xml, table_to_xml, xpath… и XML вообще
  return DENIED_PREFIXES.some((prefix) => lower.startsWith(prefix))
}

export function isAllowedFunction(name: string): boolean {
  return ALLOWED_FUNCTIONS.has(name)
}

/**
 * Типы в приведениях (`::тип`, `CAST`, списки столбцов функций). Нет reg*-типов
 * (поиск по каталогу: `'pg_sleep'::regproc`, `'…'::regclass`), xml, oid и
 * составных типов таблиц.
 */
const ALLOWED_TYPES = new Set([
  'bool',
  'int2',
  'int4',
  'int8',
  'float4',
  'float8',
  'numeric',
  'text',
  'varchar',
  'bpchar',
  'date',
  'time',
  'timetz',
  'timestamp',
  'timestamptz',
  'interval',
  'uuid',
  'json',
  'jsonb',
  'jsonpath',
  'bytea',
  'bit',
  'varbit',
  'tsvector',
  'tsquery',
  'geometry',
  'geography',
  'box2d',
  'box3d',
])

export function isAllowedType(name: string): boolean {
  return ALLOWED_TYPES.has(name)
}

/** SQL-функции времени без скобок (CURRENT_DATE…): служебные (CURRENT_USER…) запрещены. */
export const TIME_VALUE_FUNCTIONS = new Set([
  'SVFOP_CURRENT_DATE',
  'SVFOP_CURRENT_TIME',
  'SVFOP_CURRENT_TIME_N',
  'SVFOP_CURRENT_TIMESTAMP',
  'SVFOP_CURRENT_TIMESTAMP_N',
  'SVFOP_LOCALTIME',
  'SVFOP_LOCALTIME_N',
  'SVFOP_LOCALTIMESTAMP',
  'SVFOP_LOCALTIMESTAMP_N',
])

/** Имя результата для SQL-функций времени (как в FigureColname Postgres). */
export const TIME_VALUE_NAMES: Readonly<Record<string, string>> = {
  SVFOP_CURRENT_DATE: 'current_date',
  SVFOP_CURRENT_TIME: 'current_time',
  SVFOP_CURRENT_TIME_N: 'current_time',
  SVFOP_CURRENT_TIMESTAMP: 'current_timestamp',
  SVFOP_CURRENT_TIMESTAMP_N: 'current_timestamp',
  SVFOP_LOCALTIME: 'localtime',
  SVFOP_LOCALTIME_N: 'localtime',
  SVFOP_LOCALTIMESTAMP: 'localtimestamp',
  SVFOP_LOCALTIMESTAMP_N: 'localtimestamp',
}

/** Оператор без схемы: только символы операторов Postgres. */
export const OPERATOR = /^[+\-*/<>=~!@#%^&|`?]+$/
