/**
 * Вся схема БД — сборка схем владельцев таблиц (ADR-0178). Таблица описана у
 * владельца: область ядра — `kernel/<область>/schema.ts`, модуль —
 * `modules/<модуль>/schema.ts`. Сборка нужна только инструментам: drizzle-kit,
 * сиду, CLI и тестам. Код ядра и модулей импортирует таблицы из схемы владельца —
 * так dependency-cruiser видит, чьи таблицы читает модуль.
 */
export * from './kernel/access/schema.js'
export * from './kernel/acknowledgments/schema.js'
export * from './kernel/activity/schema.js'
export * from './kernel/announcements/schema.js'
export * from './kernel/audit/schema.js'
export * from './kernel/backup/schema.js'
export * from './kernel/business-calendar/schema.js'
export * from './kernel/collab/schema.js'
export * from './kernel/directory/schema.js'
export * from './kernel/discussions/schema.js'
export * from './kernel/events/schema.js'
export * from './kernel/inbox/schema.js'
export * from './kernel/jobs/schema.js'
export * from './kernel/links/schema.js'
export * from './kernel/notifications/schema.js'
export * from './kernel/objects/schema.js'
export * from './kernel/process/schema.js'
export * from './kernel/schedules/schema.js'
export * from './kernel/search/schema.js'
export * from './kernel/settings/schema.js'
export * from './kernel/spaces/schema.js'
export * from './kernel/tags/schema.js'
export * from './kernel/views/schema.js'
export * from './modules/ai/schema.js'
export * from './modules/alerts/schema.js'
export * from './modules/automation/schema.js'
export * from './modules/calendar/schema.js'
export * from './modules/chat/schema.js'
export * from './modules/data/schema.js'
export * from './modules/documents/schema.js'
export * from './modules/files/schema.js'
export * from './modules/forms/schema.js'
export * from './modules/gis/schema.js'
export * from './modules/identity/schema.js'
export * from './modules/integrations/schema.js'
export * from './modules/knowledge/schema.js'
export * from './modules/mail/schema.js'
export * from './modules/meetings/schema.js'
export * from './modules/push/schema.js'
export * from './modules/reports/schema.js'
export * from './modules/tasks/schema.js'
export * from './modules/telegram/schema.js'
export * from './modules/territories/schema.js'
export * from './shared/db/columns.js'
